version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.node
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis

  inference-api:
    build:
      context: ../hazard-detection-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../hazard-detection-api:/app

  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"

