[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
restartPolicyType = "always"
numReplicas = 1

[environments.production.variables]
NODE_ENV = "production"
MODEL_DIR = "/app/api/best_openvino_model"
API_URL = "http://localhost:8001"