[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.unified"

[deploy]
startCommand = "bash scripts/start-united.sh"


[deploy.env]
# Railway automatically provides PORT - don't override unless needed
NODE_ENV = "production"
MODEL_BACKEND = "auto"
MODEL_DIR = "/app"
PYTHONPATH = "/app"

# Cloudinary Configuration (set actual values in Railway dashboard)
CLOUDINARY_CLOUD_NAME = ""
CLOUDINARY_API_KEY = ""
CLOUDINARY_API_SECRET = ""

# Session Configuration
SESSION_SECRET = ""

# SendGrid Configuration
SENDGRID_API_KEY = ""

# Redis Configuration
REDIS_HOST = ""
REDIS_PORT = ""
REDIS_USERNAME = ""
REDIS_PASSWORD = ""

# Google OAuth Configuration
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_CALLBACK_URL = ""

# Google Maps/Geocoding API
GOOGLE_GEOCODING_API_KEY = ""
GOOGLE_MAPS_API_KEY = ""

# API Integration - Need to determine correct API service URL
API_URL = ""
HAZARD_API_URL = ""

# Railway Public Domain Configuration - Updated to match actual deployed URL
RENDER_EXTERNAL_URL = ""
RAILWAY_PUBLIC_DOMAIN = ""

[[sharedEnvironments]]
project = "hazard-api-production"
name = "production"
