# This file configures your deployment on Railway.
# For more information, see the Railway documentation: https://docs.railway.app/reference/railway-toml

[build]
# This command installs your Node.js dependencies from package.json.
# Railway runs this in your project's root directory before deploying.
buildCommand = "npm install"

[deploy]
# This command starts your Node.js server after the build is complete.
# IMPORTANT: If your main server file is not 'server.js', change it here (e.g., 'index.js').
# Alternatively, if you have a "start" script in your package.json, you can use "npm start".
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10