[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.unified"

[deploy]
startCommand = "npm start"

[deploy.kv]
PORT = "3000"

API_URL = "https://hazard-detection-api-production.up.railway.app"

[[sharedEnvironments]]
project = "hazard-detection-api-production"
name = "production"
