# This file configures your deployment on Railway.
# For more information, see the Railway documentation: https://docs.railway.app/reference/railway-toml

[build]
# This command installs your Node.js dependencies from package.json.
# Railway runs this in your project's root directory before deploying.
buildCommand = "npm install"

[deploy]
# This command starts your Node.js server after the build is complete.
# Use the start script from package.json which runs server/routes/server.js
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
