[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.unified"

[deploy]
startCommand = "npm start"

[deploy.kv]
# Railway automatically provides PORT - don't override unless needed
NODE_ENV = "production"

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME = "dgn5da9f8"
CLOUDINARY_API_KEY = "688173149321172"
CLOUDINARY_API_SECRET = "Mb_3IFGPoWA1_AM-XzOd6AH_Pyg"

# Session Configuration
SESSION_SECRET = "aVeryStrongAndRandomSecretKeyForYourSessionManagement123!@#$"

# SendGrid Configuration
SENDGRID_API_KEY = "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"

# Redis Configuration
REDIS_HOST = "redis-13437.c44.us-east-1-2.ec2.redns.redis-cloud.com"
REDIS_PORT = "13437"
REDIS_USERNAME = "default"
REDIS_PASSWORD = "e7uFJGU10TYEVhTJFoOkyPog0fBMhJMG"

# Google OAuth Configuration
GOOGLE_CLIENT_ID = "46375555882-rmivba20noas9slfskb3cfvugssladrr.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_CALLBACK_URL = "https://hazard-detection-production.up.railway.app/auth/google/callback"

# Google Maps/Geocoding API
GOOGLE_GEOCODING_API_KEY = "AIzaSyAJ4073PjQ5koFcU9O3WCt8IsK43NNMPcc"
GOOGLE_MAPS_API_KEY = "AIzaSyAJ4073PjQ5koFcU9O3WCt8IsK43NNMPcc"

# API Integration - Fixed URL format
API_URL = "https://hazard-api-production-production.up.railway.app"
HAZARD_API_URL = "https://hazard-api-production-production.up.railway.app"

# Railway Public Domain Configuration
RENDER_EXTERNAL_URL = "https://hazard-detection-production.up.railway.app"
RAILWAY_PUBLIC_DOMAIN = "hazard-detection-production.up.railway.app"

[[sharedEnvironments]]
project = "hazard-api-production"
name = "production"
