[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.unified"

[deploy]
startCommand = "/app/start-unified.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.kv]
PORT = "8080"
NODE_ENV = "production"
